import type { Settings } from './types';

export const DEFAULT_SETTINGS: Settings = {
  globalEnabled: true,
  language: 'en',
  theme: 'system',

  features: {
    runner: true,
    copy: true,
    collapse: true,
    languageLabel: true,
    lineNumbers: true,
    diff: true,
    toc: true,
    progressBar: true,
  },

  foldThreshold: 20,
  executionTimeout: 5,
  diffViewMode: 'side-by-side',

  siteListMode: 'blacklist',
  siteList: [],
};

export const RUNNABLE_LANGUAGES = new Set([
  'javascript', 'js',
  'typescript', 'ts',
  'html',
  'css',
]);

export const LANGUAGE_ALIASES: Record<string, string> = {
  js: 'JavaScript',
  javascript: 'JavaScript',
  ts: 'TypeScript',
  typescript: 'TypeScript',
  html: 'HTML',
  css: 'CSS',
  python: 'Python',
  py: 'Python',
  java: 'Java',
  cpp: 'C++',
  'c++': 'C++',
  c: 'C',
  csharp: 'C#',
  cs: 'C#',
  go: 'Go',
  rust: 'Rust',
  rs: 'Rust',
  ruby: 'Ruby',
  rb: 'Ruby',
  php: 'PHP',
  swift: 'Swift',
  kotlin: 'Kotlin',
  kt: 'Kotlin',
  scala: 'Scala',
  shell: 'Shell',
  bash: 'Bash',
  sh: 'Shell',
  zsh: 'Shell',
  powershell: 'PowerShell',
  ps1: 'PowerShell',
  sql: 'SQL',
  json: 'JSON',
  yaml: 'YAML',
  yml: 'YAML',
  xml: 'XML',
  markdown: 'Markdown',
  md: 'Markdown',
  dockerfile: 'Dockerfile',
  docker: 'Dockerfile',
  toml: 'TOML',
  ini: 'INI',
  graphql: 'GraphQL',
  gql: 'GraphQL',
  r: 'R',
  lua: 'Lua',
  perl: 'Perl',
  dart: 'Dart',
  elixir: 'Elixir',
  ex: 'Elixir',
  clojure: 'Clojure',
  clj: 'Clojure',
  haskell: 'Haskell',
  hs: 'Haskell',
  diff: 'Diff',
  plaintext: 'Plain Text',
  text: 'Plain Text',
  txt: 'Plain Text',
};

export const STORAGE_KEY = 'markdownRunnerSettings';
export const BADGE_COLOR = '#4A90D9';
